title: "ğŸ“š Education"
items:
  - "ğŸ“ MSc Computer Science, **University of Warwick**"
  - "ğŸ“ BSc Computer Science, **Dalhousie University**"
  - "ğŸ“ Exchange Student, **City University of Hong Kong**" 