title: "ğŸ‘‹ Hi there, I'm Herman!"
subtitle: "ğŸš€ Full Stack Developer | ğŸ§  AI Enthusiast | ğŸ“ Based in Halifax, NS & Toronto, ON"
website: "https://hermanyiqunliang.com"
contact:
  email: "Hermanyiqunliang@gmail.com"
  linkedin: "https://www.linkedin.com/in/liang-yiqun/"
quote: "Build what matters. Break what needs fixing. Learn endlessly."
quote_author: "Herman" 