title: "Herman Liang"
subtitle: "Full Stack Developer"
website: "https://hermanyiqunliang.com"
address: "805-16 Rooksview Lane, Bedford, Nova Scotia"
contact:
  email: "Hermanyiqunliang@gmail.com"
  linkedin: "https://www.linkedin.com/in/liang-yiqun/"
quote: "Kindness always come back in the ways we don't expect."
quote_author: "Herman" 