title: "ğŸ•°ï¸ My Tech Journey"
timeline:
  - year: "2002"
    event: "Born in **China**"
  - year: "2015"
    event: "Built my first web scraper in Python (using BeautifulSoup) in junior high"
  - year: "2016 â€“ 2019"
    event: "Studied at **Sino-Canadian Program, Shenyang No.2 High School**"
    details:
      - "Created a **Python GUI seat selection app** for automatic rotation"
  - year: "2019 â€“ 2023"
    event: "BSc in Computer Science, **Dalhousie University**"
    details:
      - "**2020** â€” Built my first **PHP-based web application**"
      - "**2022 (Jan â€“ May)** â€” Exchange at **City University of Hong Kong**, focusing on **Data Science** - Developed an **award-winning PPT comment app** in PHP"
      - "**Sep 2022** â€” Built my first **Angular-based web app** for coursework"
      - "**2023** â€” Work with team to create a **Next.js MERN stack final-year project**"
  - year: "2023 â€“ 2024"
    event: "MSc in Computer Science, **University of Warwick**"
  - year: "Dec 2023"
    event: "Retrieved Azure Cloud Certificate"
  - year: "Feb 2024"
    event: "Led 1Way team to build a **Flutter + NestJS-based taxi platform**"
  - year: "May 2024"
    event: "Released"
    details:
      - "An **Electron-based End-to-End Encryption app** for WeChat"
      - "A **Java-based E2EE keyboard mobile app**"
  - year: "Feb 2025"
    event: "Built my first **Rust + Solana/Koii decentralized app**"
footer: "**...The journey continues. ğŸš€**" 